version: '2'

services:
  ml-backend:
    image: node:latest
    container_name: dariodiaz-ml-backend
    ports:
      - 4000:4000
    volumes:
      - ./backend/:/backend/
    command: ["node", "/backend/index.js"]
    #restart: always
  
  ml-frontend:
    image: nginx
    container_name: dariodiaz-ml-frontend
    ports:
      - 8082:80
    volumes:
      - ./frontend/build/:/usr/share/nginx/html